### ISSUE TITLE
Auth-only version?

### ISSUE THREAD

**Issue by ProLoser** [tarlepp/angular-sailsjs-boilerplate#52]
So I'm getting a headache trying to add the massive amounts of logic required from a blank app to get socket+passport auth working, and I'm getting a headache trying to take out things in your boilerplate that I don't want, which causes everything to break because you've dispersed the logic all over the place.

Is there ANY chance you could make a fork or branch or something that ONLY contains the auth and front/back separation? I don't want all the GUI tweaks, I just want passport and auth working for a separated front/back. I've spent like 12 hours trying to get this done and it's giving me a headache.

**Comment by tarlepp** [comment]
seems like you have already copied this project and made something different. I would hope that you would make fork instead of copy+paste option. Closing this now, but I think I'm going to make "proper" version of this... at sometime...

**Comment by SudoPlz** [comment]
I'm interested in this as well!

**Comment by veswill3** [comment]
I also think this would be a good idea and I am willing to do a pull request but I need get a more complete understanding of it all before that. I know what they mean about the code being spread out but the more I stare at it and hack with it the more I appreciate how it is set up. Its very modular actually.

I think this could all be in one repository, but on separate branches.
* `starting-place`: A bare bones boilerplate with all the goodies.
* `example`: All the Author/Book/etc stuff built on top of `starting-place`.

I think the main advantage here is that we could fork `starting-place` to make our own projects and reference `example`. Then if you add a new utility to the project, you would add it to `starting-place` and merge it into `example`. Similarly, we could pull those commits into our forks, since they wont include example code.

**Comment by SudoPlz** [comment]
@veswill3 I'm willing to help you with that, with my limited knowledge on this, if you got time. We can hook up in skype and start working on this if you want to.

**Comment by veswill3** [comment]
I would like to do that sometime @SudoPlz. Give me a few days to get a better understanding of all this first. Maybe like Tuesday of next week? We can chat outside of this issue.

**Comment by SudoPlz** [comment]
Sure @veswill3. The reason I wanna do this to learn. My skype name is 'sudoplz' add me if you want.

**Comment by ProLoser** [comment]
@SudoPlz hah, I don't think my fork is stripped down enough!

**Comment by tarlepp** [comment]
Hmm, I think that the separate repo/branch is the way to go with this one. But really it's nice to see there is need for this too...

**Comment by ProLoser** [comment]
@tarlepp i wasn't saying it shouldn't be a separate repo. I just needed it way more than most of the other stuff in here.

**Comment by tarlepp** [comment]
@ProLoser I noticed your comment after I did post my...

**Comment by tarlepp** [comment]
@SudoPlz and @veswill3 I'm also interested of that skype chat if you're planning to do that.
