### ISSUE TITLE
Support for cg-angular Yeoman Generator

### ISSUE THREAD

**Issue by ksambhav** [tarlepp/angular-sailsjs-boilerplate#92]
For the front-end module, use 'generator-cg-angular' yemoan generator instead of angular-slush.

https://github.com/cgross/generator-cg-angular

Benefits of cg-angular :-

1. Configuration to use UI-Router if needed and not just standard ngRouter.
2. The generator genrates both Gruntfile ang gulpfile.
3. Subgenerators for module,filter,service,partial,directive.
4. the dist have simple unglified js with template cached -> no htmls - lesser no. of files for browser to get.

**Comment by tarlepp** [comment]
Personally I don't use Yeoman at all, so I'm not going to change this behaviour at this moment. Feel free to generate your own version of frontend side with Yeoman. And if you make this to separated repo I'll add information about that to README.MD.

This is one of the main points of separation of back- and frontend, so that users can make new frontends as they like.
